-- Learning Progress Tracker - Supabase schema
-- Run this once in Supabase Dashboard > SQL Editor.

create table if not exists public.goals (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    subject text not null,
    weekly_hours double precision not null,
    target_score double precision,
    target_date date,
    created_at timestamptz not null default now()
);

create table if not exists public.study_logs (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    study_date date not null,
    subject text not null,
    minutes integer not null check (minutes > 0),
    note text,
    created_at timestamptz not null default now()
);

create table if not exists public.plans (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    week_start date not null,
    content text not null,
    created_at timestamptz not null default now()
);

alter table public.goals enable row level security;
alter table public.study_logs enable row level security;
alter table public.plans enable row level security;

-- Re-running safely: remove old policies first.
drop policy if exists "goals_select_own" on public.goals;
drop policy if exists "goals_insert_own" on public.goals;
drop policy if exists "goals_update_own" on public.goals;
drop policy if exists "goals_delete_own" on public.goals;

drop policy if exists "study_logs_select_own" on public.study_logs;
drop policy if exists "study_logs_insert_own" on public.study_logs;
drop policy if exists "study_logs_update_own" on public.study_logs;
drop policy if exists "study_logs_delete_own" on public.study_logs;

drop policy if exists "plans_select_own" on public.plans;
drop policy if exists "plans_insert_own" on public.plans;
drop policy if exists "plans_update_own" on public.plans;
drop policy if exists "plans_delete_own" on public.plans;

create policy "goals_select_own"
on public.goals for select to authenticated
using ((select auth.uid()) = user_id);

create policy "goals_insert_own"
on public.goals for insert to authenticated
with check ((select auth.uid()) = user_id);

create policy "goals_update_own"
on public.goals for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "goals_delete_own"
on public.goals for delete to authenticated
using ((select auth.uid()) = user_id);

create policy "study_logs_select_own"
on public.study_logs for select to authenticated
using ((select auth.uid()) = user_id);

create policy "study_logs_insert_own"
on public.study_logs for insert to authenticated
with check ((select auth.uid()) = user_id);

create policy "study_logs_update_own"
on public.study_logs for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "study_logs_delete_own"
on public.study_logs for delete to authenticated
using ((select auth.uid()) = user_id);

create policy "plans_select_own"
on public.plans for select to authenticated
using ((select auth.uid()) = user_id);

create policy "plans_insert_own"
on public.plans for insert to authenticated
with check ((select auth.uid()) = user_id);

create policy "plans_update_own"
on public.plans for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "plans_delete_own"
on public.plans for delete to authenticated
using ((select auth.uid()) = user_id);

grant select, insert, update, delete on public.goals to authenticated;
grant select, insert, update, delete on public.study_logs to authenticated;
grant select, insert, update, delete on public.plans to authenticated;

grant usage, select on all sequences in schema public to authenticated;

create index if not exists goals_user_id_idx on public.goals(user_id);
create index if not exists study_logs_user_id_idx on public.study_logs(user_id);
create index if not exists plans_user_id_idx on public.plans(user_id);
